name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main
      - dev
      - qa
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      INSTANCE_ID_DEV: ${{ secrets.EC2_INSTANCE_ID_DEV }}
      INSTANCE_ID_QA: ${{ secrets.EC2_INSTANCE_ID_QA }}
      INSTANCE_ID_MAIN: ${{ secrets.EC2_INSTANCE_ID_MAIN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change if you're in a different region

      - name: Detect Changes
        id: changes
        run: |
          echo "FRONTEND_CHANGED=false" >> $GITHUB_ENV
          echo "BACKEND_CHANGED=false" >> $GITHUB_ENV
          git fetch origin ${{ github.event.before }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^frontend/" && echo "FRONTEND_CHANGED=true" >> $GITHUB_ENV || true
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^backend/" && echo "BACKEND_CHANGED=true" >> $GITHUB_ENV || true

      - name: Set Instance ID
        id: set-instance
        run: |
          BRANCH=$(echo "${{ github.ref }}" | awk -F'/' '{print $3}')
          if [[ "$BRANCH" == "main" ]]; then
            echo "INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID_MAIN }}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "dev" ]]; then
            echo "INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID_DEV }}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "qa" ]]; then
            echo "INSTANCE_ID=${{ secrets.EC2_INSTANCE_ID_QA }}" >> $GITHUB_ENV
          fi

      - name: Deploy Frontend
        if: env.FRONTEND_CHANGED == 'true'
        run: |
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying Frontend" \
            --parameters commands=["bash ~/scripts/deploy-frontend.sh"] \
            --region us-east-1

      - name: Deploy Backend
        if: env.BACKEND_CHANGED == 'true'
        run: |
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying Backend" \
            --parameters commands=["bash ~/scripts/deploy-backend.sh"] \
            --region us-east-1
